# Generated by Django 3.2.4 on 2021-06-26 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifiable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_main.notifiable_set+', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Postable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_main.postable_set+', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('content', models.CharField(blank=True, default='', max_length=1000)),
                ('location', models.CharField(choices=[('General', 'General'), ('COM', 'Computing'), ('KR MRT', 'KR MRT'), ('SCI', 'SCI'), ('BIZ', 'BIZ'), ('WTV', 'WTV')], default='General', max_length=30)),
                ('tags', models.JSONField(default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('title', 'content')},
            },
        ),
        migrations.CreateModel(
            name='ThreadChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.thread')),
                ('user_list', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Anonymous', max_length=50)),
                ('year', models.CharField(choices=[('Anonymous', 'Anonymous'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='anon', max_length=10)),
                ('faculty', models.CharField(choices=[('Anonymous', 'Anonymous'), ('Business', 'Business'), ('Computing', 'Computing'), ('Science', 'Science'), ('Law', 'Law'), ('Wtv', 'Wtv')], default='Anonymous', max_length=10)),
                ('major', models.CharField(default='Anonymous', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestee_set', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester_set', to=settings.AUTH_USER_MODEL)),
                ('threadchat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.threadchat')),
            ],
            options={
                'unique_together': {('requester', 'threadchat')},
            },
        ),
        migrations.CreateModel(
            name='ThreadJoinRequestNotification',
            fields=[
                ('notifiable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.notifiable')),
                ('threadjoinrequest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.threadjoinrequest')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('main.notifiable',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('postable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.postable')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.thread')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('main.postable',),
        ),
        migrations.CreateModel(
            name='ChatPost',
            fields=[
                ('postable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.postable')),
                ('threadchat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.threadchat')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('main.postable',),
        ),
    ]
