# Generated by Django 3.2.2 on 2021-06-23 05:44

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='tags',
            field=models.JSONField(default=main.models.Thread.getTagDefault),
        ),
    ]
