# Generated by Django 3.2.2 on 2021-06-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='faculty',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='major',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.CharField(default='Anonymous', max_length=10),
        ),
    ]
