# Generated by Django 3.2.2 on 2021-06-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210603_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='faculty',
            field=models.CharField(choices=[('sci', 'Science'), ('com', 'Computing'), ('law', 'Law'), ('biz', 'Business'), ('wtv', 'Wtv')], default='com', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, default='Anonymous', max_length=50),
        ),
    ]
