# Generated by Django 3.2.2 on 2021-06-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210604_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='faculty',
            field=models.CharField(choices=[('Anonymous', 'Anonymous'), ('Business', 'Business'), ('Computing', 'Computing'), ('Science', 'Science'), ('Law', 'Law'), ('Wtv', 'Wtv')], default='anon', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.CharField(choices=[('Anonymous', 'Anonymous'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='anon', max_length=10),
        ),
    ]
